#!/bin/sh

# Kludged documentation generator to support multiple versions.
# Make sure the `site` folder is a checkout of this repository's `gh-pages`
# branch.

set -e

REMOTE=$(git remote get-url origin)
CHECKOUT="$(mktemp -d)"
OUTPUT="$(pwd)/site"

if [ -d site ]
then
	cd site
	git pull
else
	git clone "$REMOTE" site
	cd site
	git checkout gh-pages
fi

git clone "$REMOTE" "$CHECKOUT"
cd "$CHECKOUT"

echo "Building master"
git checkout master
mkdocs build --site-dir "$OUTPUT"

echo "Building 0.5.x"
mkdocs build --site-dir "$OUTPUT/0.5.x"

echo "Building 0.4.x"
git checkout v0.4.x
mkdocs build --site-dir "$OUTPUT/0.4.x"