return function()
	local Theme = require(script.Parent.Theme)

	describe("Prism theme", function()
		it("defines the centralized glass UI tokens", function()
			local tokens = Theme.Tokens
			expect(tokens.PanelBackground).to.be.ok()
			expect(tokens.CardBackground).to.be.ok()
			expect(tokens.ElevatedCardBackground).to.be.ok()
			expect(tokens.Border).to.be.ok()
			expect(tokens.PrimaryText).to.be.ok()
			expect(tokens.SecondaryText).to.be.ok()
			expect(tokens.MutedText).to.be.ok()
			expect(tokens.PrimaryAccent).to.be.ok()
			expect(tokens.Success).to.be.ok()
			expect(tokens.Warning).to.be.ok()
			expect(tokens.Danger).to.be.ok()
			expect(tokens.ButtonHover).to.be.ok()
			expect(tokens.ButtonPressed).to.be.ok()
			expect(tokens.InputBackground).to.be.ok()
			expect(tokens.InputBorder).to.be.ok()
			expect(tokens.OverlayDarkness >= 0.5).to.equal(true)
			expect(tokens.OverlayDarkness <= 0.8).to.equal(true)
		end)
	end)
end
