return function()
	local Branding = require(script.Parent.Branding)

	describe("Prism branding", function()
		it("uses the uploaded Prism identity", function()
			expect(Branding.Name).to.equal("Prism")
			expect(Branding.Tagline).to.equal("Studio automation for Roblox")
			expect(Branding.FullLogoAssetId).to.equal("rbxassetid://78583834238790")
			expect(Branding.IconAssetId).to.equal("rbxassetid://84145747248222")
			expect(Branding.WarningAssetId).to.equal("rbxassetid://130567248372259")
			expect(Branding.AssetId).to.equal("rbxassetid://84145747248222")
			expect(Branding.DockWidgetTitlePrefix).to.equal("Prism ")
		end)

		it("maps normal and degraded toolbar states to Prism assets", function()
			local Assets = require(script.Parent.Assets)
			expect(Assets.Images.PluginButton).to.equal(Branding.IconAssetId)
			expect(Assets.Images.PluginButtonConnected).to.equal(Branding.IconAssetId)
			expect(Assets.Images.PluginButtonWarning).to.equal(Branding.WarningAssetId)
		end)

		it("retains Studio compatibility identifiers", function()
			expect(Branding.Compatibility.DockWidgetIdPrefix).to.equal("Rojo ")
			expect(Branding.Compatibility.ToolbarButtonId).to.equal("Rojo")
			expect(Branding.Compatibility.ToggleActionId).to.equal("RojoConnection")
			expect(Branding.Compatibility.ConnectActionId).to.equal("RojoConnect")
			expect(Branding.Compatibility.DisconnectActionId).to.equal("RojoDisconnect")
		end)
	end)
end
